version: '2'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  coordinator:
    build:
      context: .
      args:
        - LAUNCH_TYPE=coordinator
        - LISTEN_PORT=8080
    ports:
      - "8080:8080"
  worker:
    build:
      context: .
      args:
        - LAUNCH_TYPE=worker
        - LISTEN_PORT=8081
    ports:
      - "8081:8081"
