version: '2'

services:
  first_mysql:
    image: mysql:5.7
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - first_mysql:/var/lib/mysql
  second_mysql:
    image: mysql:5.7
    ports:
      - "33062:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - second_mysql:/var/lib/mysql
  coordinator:
    build:
      context: .
      args:
        - LAUNCH_TYPE=coordinator
        - LISTEN_PORT=8080
    ports:
      - "8080:8080"
  worker:
    build:
      context: .
      args:
        - LAUNCH_TYPE=worker
        - LISTEN_PORT=8081
    ports:
      - "8081:8081"
  presto-cli:
    build:
      context: .
      dockerfile: Dockerfile-presto-cli

volumes:
    first_mysql:
        driver: 'local'
    second_mysql:
        driver: 'local'
